### ISSUE TITLE
update to the code with the function parameter

### ISSUE THREAD

**Issue by e-thibault** [twin-bridges/learning_python#1]
Hello,
In twin-bridges / learning_Python
https://github.com/twin-bridges/learning_python/tree/main/lesson6/exercise4.py

I stumbled upon a tiny issue in line 25:
"write(telnet_conn, "pyclass\n")"
in fact instead of "pyclass" it should be updated with the "username" parameter of the login function, I copied your syntax for password and it becomes:
"write(telnet_conn, f"{username}\n")"

I tested on my GNS3 lab and it works.
Thanks for your python course, great content !

**Comment by ktbyers** [comment]
Fixed.
